export const personajes = [

    {
        id: 1,
        estandarte: './Gryffindor_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/harry.jpg',
        name: 'Harry Potter',
        casa: 'Gryffindor',

    },
    {
        id: 2,
        estandarte: './Gryffindor_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/hermione.jpeg',
        name: 'Hermione Granger',
        casa: 'Gryffindor',
    },
    {
        id: 3,
        estandarte: './Gryffindor_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/ron.jpg',
        name: 'Ron Weasley',
        casa: 'Gryffindor',
    },
    {
        id: 4,
        estandarte: './Gryffindor_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/neville.jpg',
        name: 'Neville Longbottom',
        casa: 'Gryffindor',
    },
    {
        id: 5,
        estandarte: './Gryffindor_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/ginny.jpg',
        name: 'Ginny Weasley',
        casa: 'Gryffindor',
    },
    {
        id: 6,
        estandarte: './Hufflepuff_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/cedric.png',
        name: 'Cedric Diggory',
        casa: 'Hufflepuff',
    },
    {
        id: 7,
        estandarte: './Hufflepuff_Pottermore.png',
        foto: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/fac67f3e-e06c-4a51-81fc-2f59b7b01f3b/dttlwb-8c7378e1-2cec-40af-b6e0-f4828fd856b8.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2ZhYzY3ZjNlLWUwNmMtNGE1MS04MWZjLTJmNTliN2IwMWYzYlwvZHR0bHdiLThjNzM3OGUxLTJjZWMtNDBhZi1iNmUwLWY0ODI4ZmQ4NTZiOC5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.WAZ4XMroe55aHTr9ykzQmTk34MItaYJErilvxeffaro',
        name: 'Zacharias Smith',
        casa: 'Hufflepuff',
    },
    {
        id: 8,
        estandarte: './Hufflepuff_Pottermore.png',
        foto: 'https://i.pinimg.com/736x/65/23/8f/65238f5efd3550fa15f268b467d13e80.jpg',
        name: 'Newton Scamander',
        casa: 'Hufflepuff',
    },
    {
        id: 9,
        estandarte: './Hufflepuff_Pottermore.png',
        foto: 'https://i.pinimg.com/550x/9d/2c/6e/9d2c6e1a8b3b3bf5abd02655753c15ca.jpg',
        name: 'Theseus Scamander',
        casa: 'Hufflepuff',
    },
    {
        id: 10,
        estandarte: './Hufflepuff_Pottermore.png',
        foto: 'https://pbs.twimg.com/profile_images/1091175636650078214/71iV555C_400x400.jpg',
        name: 'Pomona Sprout',
        casa: 'Hufflepuff',
    },
    {
        id: 11,
        estandarte: './Ravenclaw_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/cho.jpg',
        name: 'Cho Chang',
        casa: 'Ravenclaw',
    },
    {
        id: 12,
        estandarte: './Ravenclaw_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/luna.jpg',
        name: 'Luna Lovegood',
        casa: 'Ravenclaw',
    },
    {
        id: 13,
        estandarte: './Ravenclaw_Pottermore.png',
        foto: 'https://pbs.twimg.com/media/D1O48S5XcAAwsxN.jpg',
        name: 'Sybill Patricia Trelawney',
        casa: 'Ravenclaw',
    },
    {
        id: 14,
        estandarte: './Ravenclaw_Pottermore.png',
        foto: 'http://pm1.narvii.com/6918/73dcd4500d1dad1ff53cfd37d25804dec5df39f5r1-287-364v2_uhq.jpg',
        name: 'Myrtle Elizabeth Warren',
        casa: 'Ravenclaw',
    },
    {
        id: 15,
        estandarte: './Ravenclaw_Pottermore.png',
        foto: 'https://img.buzzfeed.com/buzzfeed-static/static/2017-08/16/0/enhanced/buzzfeed-prod-web-15/enhanced-17957-1502857782-1.jpg',
        name: 'Penelope Clearwater',
        casa: 'Ravenclaw',
    },
    {
        id: 16,
        estandarte: './Slytherin_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/draco.jpg',
        name: 'Draco Malfoy',
        casa: 'Slytherin',
    },
    {
        id: 17,
        estandarte: './Slytherin_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/crabbe.jpg',
        name: 'Vincent Crabbe',
        casa: 'Slytherin',
    },
    {
        id: 18,
        estandarte: './Slytherin_Pottermore.png',
        foto: 'http://hp-api.herokuapp.com/images/goyle.jpg',
        name: 'Gregory Goyle',
        casa: 'Slytherin',
    },
    {
        id: 19,
        estandarte: './Slytherin_Pottermore.png',
        foto: 'https://pbs.twimg.com/profile_images/928036938598232064/YClCUwDE_400x400.jpg',
        name: 'Flora Carrow',
        casa: 'Slytherin',
    },
    {
        id: 20,
        estandarte: './Slytherin_Pottermore.png',
        foto: 'https://i.pinimg.com/736x/83/91/95/839195114c774198cdf7a9c78fd46460.jpg',
        name: 'Tom Ryddle',
        casa: 'Slytherin',
    },


];